name = "failover-proxy"
main = "worker.js"
compatibility_date = "2023-09-04"

# Configure KV namespaces for persistent storage (optional)
# [kv_namespaces]
# [[kv_namespaces]]
# binding = "METRICS"
# id = "<YOUR_KV_NAMESPACE_ID>"
# Configure Durable Object namespaces (optional)
# [durable_objects]
# bindings = [
#   { name = "METRICS", class_name = "MetricsObject" }
# ]
# [[migrations]]
# tag = "v1"
# new_classes = ["MetricsObject"]
# Configure routes for your worker
# workers.dev will serve the dashboard
# Routes pattern will handle the failover scenarios
[triggers]
crons = ["*/5 * * * *"] # Run health checks every 5 minutes

# Environment variables
[vars]
ENVIRONMENT = "production"
CLOUDFLARE_API_KEY="34a4d9943975b89dd2430870ce146f26aa5bf"
CLOUDFLARE_API_TOKEN="InPh1B7EmFCqAUbG2STUs5sGRyzIY266-sRK0CWy"
CLOUDFLARE_EMAIL="boden.crouch@gmail.com"
CLOUDFLARE_ZONE_ID="164c8d72507295b51851d9b05f0e37a1"

# Development environment
[env.dev]
name = "failover-proxy-dev"
vars = { ENVIRONMENT = "development" }

# Production environment
[env.production]
routes = [
  # Add your domains here, e.g.:
  { pattern = "failover-proxy.bodencrouch.com/*", zone_name = "bodencrouch.com" },
  { pattern = "*.bolabaden.org/*", zone_name = "bodencrouch.com" }
]

[observability.logs]
enabled = true
